import React, { lazy, Suspense, useState, useEffect } from 'react';
import { Box } from '@mui/material';
import Editor from '../components/ui/Editor';
import ButtonAppBar from '../components/ui/Navbar';
import Loading from '../components/ui/Loading';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Button,
  Typography
} from '@mui/material';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';

// Lazy-loaded components
const Footer = lazy(() => import('../components/ui/Footer'));
const Sidebar = lazy(() => import('../components/ui/Sidebar'));
const Sidebar2 = lazy(() => import('../components/ui/Sidebar2'));

const Home = () => {
  const [generatedCode, setGeneratedCode] = useState('');
  const [styleOptions, setStyleOptions] = useState({
    framework: 'Tailwind CSS',
    colorScheme: 'blue',
    size: 'medium',
    rounded: 'medium',
  });

  // Modal warning state
  const [openWarning, setOpenWarning] = useState(true);

  useEffect(() => {
    setOpenWarning(true);
    // Optional: only show once per session
    // const seen = localStorage.getItem('aiWarningSeen');
    // if (!seen) {
    //   setOpenWarning(true);
    //   localStorage.setItem('aiWarningSeen', 'true');
    // } else {
    //   setOpenWarning(false);
    // }
  }, []);

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        backgroundColor: '#f9fafb',
      }}
    >
      {/* Navbar */}
      <Suspense fallback={<Loading type="ButtonAppBar" />}>
        <ButtonAppBar />
      </Suspense>

      {/* Main content area */}
      <Box
        sx={{
          flex: 1,
          display: 'flex',
          flexDirection: { xs: 'column', md: 'row' },
          px: { xs: 2, md: 3 },
          py: { xs: 2, md: 3 },
          gap: 2,
          mt: { xs: 0, md: -1 },
        }}
      >
        {/* Sidebars */}
        <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            width: { xs: '100%', md: '480px' },
            mt: { xs: 0, md: -2 },
          }}
        >
          <Suspense fallback={<Loading type="Sidebar" />}>
            <Sidebar setGeneratedCode={setGeneratedCode} styleOptions={styleOptions} />
          </Suspense>

          <Suspense fallback={<Loading type="Sidebar2" />}>
            <Sidebar2 styleOptions={styleOptions} setStyleOptions={setStyleOptions} />
          </Suspense>
        </Box>

        {/* Editor */}
        <Box sx={{ flex: 1, width: '100%', mt: { xs: 0, md: 2 }, gap: 2 }}>
          <Editor generatedCode={generatedCode} />
        </Box>
      </Box>

      {/* Warning Dialog */}
      <Dialog
        open={openWarning}
        onClose={() => setOpenWarning(false)}
        aria-labelledby="ai-warning-title"
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <WarningAmberIcon color="warning" />
          <Typography variant="h6" id="ai-warning-title" color="warning.main">
            AI Disclaimer
          </Typography>
        </DialogTitle>
        <DialogContent dividers>
          <DialogContentText>
            The result generated by the AI may contain serious issues. Please verify outputs carefully before using them in production or important environments.
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button
            onClick={() => setOpenWarning(false)}
            variant="contained"
            color="primary"
            fullWidth
          >
            Continue
          </Button>
        </DialogActions>
      </Dialog>
      <Suspense fallback={<Loading type="Footer" />}>
        <Footer />
      </Suspense>
    </Box>
  );
};

export default Home;
