import React, { useEffect, useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Button,
  Typography,

} from '@mui/material';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';

const Warningmessage = () => {
  const [open, setOpen] = useState(true);

  useEffect(() => {
    setOpen(true);
  }, []);

  const handleClose = () => {
    setOpen(false);
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      aria-labelledby="ai-warning-title"
      maxWidth="sm"
      fullWidth
    >
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <WarningAmberIcon color="warning" />
        <Typography variant="h6" id="ai-warning-title" color="warning.main">
          AI Disclaimer
        </Typography>
      </DialogTitle>
      <DialogContent dividers>
        <DialogContentText>
          The result generated by the AI may contain serious issues. Please verify outputs carefully before using them in production or important environments.
        </DialogContentText>
      </DialogContent>
      <DialogActions>
        <Button
          onClick={handleClose}
          variant="contained"
         sx={{
            background: 'linear-gradient(to right, #4f46e5, #9333ea)'}}
          fullWidth
        >
          Continue
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default Warningmessage;
