import React, { useEffect, useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
} from '@mui/material';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';

const Warningmessage = () => {
  const [open, setOpen] = useState(true);

  useEffect(() => {
    setOpen(true);
  }, []);

  const handleClose = () => setOpen(false);

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      aria-labelledby="ai-warning-title"
      maxWidth="sm"
      fullWidth
      PaperProps={{
        sx: { borderRadius: 3, boxShadow: 8 },
      }}
    >
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <WarningAmberIcon color="warning" />
        <Typography variant="h6" id="ai-warning-title" color="warning.main">
          AI Disclaimer
        </Typography>
      </DialogTitle>

      <DialogContent dividers>
        <Typography variant="body1" color="text.secondary">
          The result generated by the AI may contain serious issues. Please verify outputs carefully before using them in production or important environments.
        </Typography>
      </DialogContent>

      <DialogActions>
        <Button
          onClick={handleClose}
          variant="contained"
          fullWidth
          sx={{
            backgroundColor: '#4f46e5', 
            color: '#fff',
            '&:hover': {
              backgroundColor: '#4338ca',
            },
            textTransform: 'none',
            fontWeight: 600,
            py: 1.5,
          }}
        >
          Continue
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default Warningmessage;
